# Generated by Django 3.0.3 on 2020-03-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='cur',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
